### PR TITLE
Add link to GitHub repo at the top of the page

### PR DESCRIPTION
**Pull request by Enselic**

### CODE REVIEW

**Comment by Enselic** [comment]
I added instructions on how to find closed issues, so this PR has a semantic merge conflict with https://github.com/oli-obk/fixmeh/pull/8. Once that is merged, we can merge this PR. There are no code conflicts though.

**Comment by oli-obk** [comment]
Lots of pages have this github link thing in the right top corner. Is that something that would be easy to integrate instead of adding a manual link?

**Comment by Enselic** [comment]
Not trivial given that we use maud, I'm afraid. We can't just copy-paste existing solutions. Likely not hard either, I just find it a bit hard to summon the energy to do it.

We can leave this PR open for a while, maybe I'll get the vibe to do it soonish.

**Comment by oli-obk** [comment]
Nah. I was hoping github had like a CSS snippet or sth trivial for us to add

**Pull request merged**
